#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"
# "$1": 这是一个 shell 脚本参数，它代表传递给脚本的第一个参数。
# 在 Git 钩子中，$1 通常是一个包含提交信息的临时文件的路径。
# 当使用 --edit 选项时，如果提供了这个参数，commitlint 将会检查该文件中的提交信息